# Generated by Django 5.2.15 on 2026-06-14 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPCState',
            fields=[
                ('npc_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('hp', models.IntegerField()),
                ('position', models.JSONField(default=list)),
                ('loot_dropped', models.BooleanField(default=False)),
                ('mood', models.CharField(default='neutral', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hp', models.IntegerField(default=100)),
                ('max_hp', models.IntegerField(default=100)),
                ('mana', models.IntegerField(default=50)),
                ('max_mana', models.IntegerField(default=50)),
                ('level', models.IntegerField(default=1)),
                ('gold', models.IntegerField(default=0)),
                ('kill_count', models.IntegerField(default=0)),
                ('race', models.CharField(default='human', max_length=32)),
                ('faction', models.CharField(default='alliance', max_length=32)),
                ('position', models.JSONField(default=list)),
                ('yaw', models.FloatField(default=0.0)),
                ('active_quests', models.JSONField(default=list)),
                ('equipped', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorldObject',
            fields=[
                ('object_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('params', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NPCRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc_id', models.CharField(max_length=64)),
                ('player', models.CharField(max_length=20)),
                ('relationship_score', models.IntegerField(default=0)),
                ('mood', models.CharField(default='neutral', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('npc_id', 'player')},
            },
        ),
        migrations.CreateModel(
            name='CompletedQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.CharField(max_length=64)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed', to='gamedata.player')),
            ],
            options={
                'unique_together': {('player', 'quest_id')},
            },
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=64)),
                ('quantity', models.IntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gamedata.player')),
            ],
            options={
                'unique_together': {('player', 'item_name')},
            },
        ),
    ]
