# Generated by Django 5.2.15 on 2026-06-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedquest',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
